[package]
org = "nust"
name = "library_service"
version = "1.0.0"
authors = ["Your Name"]
license = ["Apache-2.0"]
description = "Library Management System"

[build-options]
observabilityIncluded = true

[dependencies]
"ballerina/http" = "2.10.0"
"ballerina/log" = "2.9.0"
"ballerina/time" = "2.4.0"
"ballerina/io" = "1.6.0"